[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10.2.4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200